from __future__ import annotations

import numpy as np
from numpy.typing import NDArray
from typing import Any

def ttest_ind(x: NDArray[np.float64], y: NDArray[np.float64], equal_var: bool = True) -> dict[str, Any]: ...
def welch_ttest(x: NDArray[np.float64], y: NDArray[np.float64]) -> dict[str, Any]: ...
def mann_whitney(x: NDArray[np.float64], y: NDArray[np.float64]) -> dict[str, Any]: ...
def cohens_d(x: NDArray[np.float64], y: NDArray[np.float64]) -> dict[str, Any]: ...
def hedges_g(x: NDArray[np.float64], y: NDArray[np.float64]) -> dict[str, Any]: ...
def confidence_interval(data: NDArray[np.float64], level: float = 0.95, method: str = "t") -> dict[str, Any]: ...
def bootstrap_ci(data: NDArray[np.float64], n_bootstrap: int = 1000, confidence: float = 0.95, seed: int | None = None) -> dict[str, Any]: ...
def adjust_pvalues(p_values: NDArray[np.float64], method: str = "benjamini_hochberg", alpha: float = 0.05) -> dict[str, Any]: ...
def sample_size_for_power(effect_size: float, alpha: float = 0.05, power: float = 0.8) -> dict[str, Any]: ...
def power_for_sample_size(n: int, effect_size: float, alpha: float = 0.05) -> dict[str, Any]: ...
def durbin_watson(residuals: NDArray[np.float64]) -> float: ...
def descriptive_stats(data: NDArray[np.float64]) -> dict[str, Any]: ...
def normality_test(data: NDArray[np.float64]) -> dict[str, Any]: ...
def correlation(x: NDArray[np.float64], y: NDArray[np.float64], confidence: float = 0.95) -> dict[str, Any]: ...

__all__ = [
    "ttest_ind",
    "welch_ttest",
    "mann_whitney",
    "cohens_d",
    "hedges_g",
    "confidence_interval",
    "bootstrap_ci",
    "adjust_pvalues",
    "sample_size_for_power",
    "power_for_sample_size",
    "durbin_watson",
    "descriptive_stats",
    "normality_test",
    "correlation",
]
