from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

__all__ = [
    "PCA",
    "IncrementalPCA",
    "TruncatedSVD",
    "LDA",
    "QuadraticDiscriminantAnalysis",
    "FactorAnalysis",
    "TSNE",
]

class PCA:
    def __init__(self, n_components: int | None = None, whiten: bool = False) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> PCA: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def inverse_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class IncrementalPCA:
    def __init__(self, n_components: int | None = None, whiten: bool = False, batch_size: int | None = None) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> IncrementalPCA: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def partial_fit(self, x: NDArray[np.float64]) -> IncrementalPCA: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class TruncatedSVD:
    def __init__(self, n_components: int = 2, n_iter: int = 5, random_state: int | None = None) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> TruncatedSVD: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class LDA:
    def __init__(self, n_components: int | None = None, shrinkage: float | None = None, tol: float = 1e-4) -> None: ...
    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> LDA: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class QuadraticDiscriminantAnalysis:
    def __init__(self, reg_param: float = 0.0, priors: list[float] | None = None, store_covariance: bool = False, tol: float = 1e-4) -> None: ...
    def decision_function(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> QuadraticDiscriminantAnalysis: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_log_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...

class FactorAnalysis:
    def __init__(self, n_factors: int | None = None, rotation: str = "none", tol: float = 1e-3, max_iter: int = 1000, random_state: int | None = None) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> FactorAnalysis: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class TSNE:
    def __init__(
        self,
        n_components: int = 2,
        perplexity: float = 30.0,
        learning_rate: float | None = None,
        max_iter: int = 1000,
        early_exaggeration: float = 12.0,
        min_grad_norm: float = 1e-7,
        metric: str = "euclidean",
        init: str = "pca",
        method: str = "auto",
        theta: float = 0.5,
        random_state: int | None = None,
    ) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> TSNE: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
