from __future__ import annotations

from ferroml import ModelCard

import numpy as np
from numpy.typing import NDArray

__all__ = [
    "GaussianProcessRegressor",
    "GaussianProcessClassifier",
    "SparseGPRegressor",
    "SparseGPClassifier",
    "SVGPRegressor",
    "RBF",
    "Matern",
    "ConstantKernel",
    "WhiteKernel",
]

class RBF:
    def __init__(self, length_scale: float = 1.0) -> None: ...

    @staticmethod
    def model_card() -> ModelCard: ...

class Matern:
    def __init__(self, length_scale: float = 1.0, nu: float = 1.5) -> None: ...

    @staticmethod
    def model_card() -> ModelCard: ...

class ConstantKernel:
    def __init__(self, constant: float = 1.0) -> None: ...

    @staticmethod
    def model_card() -> ModelCard: ...

class WhiteKernel:
    def __init__(self, noise_level: float = 1.0) -> None: ...

    @staticmethod
    def model_card() -> ModelCard: ...

class GaussianProcessRegressor:
    def __init__(self, kernel: RBF | Matern | ConstantKernel | WhiteKernel | None = None, alpha: float = 1e-10, normalize_y: bool = False) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> GaussianProcessRegressor: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_with_std(self, x: NDArray[np.float64]) -> tuple[NDArray[np.float64], NDArray[np.float64]]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...

class GaussianProcessClassifier:
    def __init__(self, kernel: RBF | Matern | ConstantKernel | WhiteKernel | None = None, max_iter: int = 50) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> GaussianProcessClassifier: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_log_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...

class SparseGPRegressor:
    def __init__(
        self,
        kernel: RBF | Matern | ConstantKernel | WhiteKernel | None = None,
        alpha: float = 0.01,
        n_inducing: int = 100,
        inducing_method: str = "kmeans",
        approximation: str = "fitc",
        normalize_y: bool = False,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> SparseGPRegressor: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_with_std(self, x: NDArray[np.float64]) -> tuple[NDArray[np.float64], NDArray[np.float64]]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...

class SparseGPClassifier:
    def __init__(
        self,
        kernel: RBF | Matern | ConstantKernel | WhiteKernel | None = None,
        n_inducing: int = 100,
        inducing_method: str = "kmeans",
        max_iter: int = 50,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> SparseGPClassifier: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_log_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...

class SVGPRegressor:
    def __init__(
        self,
        kernel: RBF | Matern | ConstantKernel | WhiteKernel | None = None,
        noise_variance: float = 1.0,
        n_inducing: int = 100,
        inducing_method: str = "kmeans",
        n_epochs: int = 100,
        batch_size: int = 256,
        learning_rate: float = 0.01,
        normalize_y: bool = False,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> SVGPRegressor: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_with_std(self, x: NDArray[np.float64]) -> tuple[NDArray[np.float64], NDArray[np.float64]]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
