from __future__ import annotations

import numpy as np
from numpy.typing import NDArray
from typing import Any

__all__ = [
    "Pipeline",
    "ColumnTransformer",
    "FeatureUnion",
    "TextPipeline",
]

class Pipeline:
    def __init__(self, steps: list[tuple[str, Any]]) -> None: ...
    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> Pipeline: ...
    def fit_transform(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def get_params(self) -> dict[str, Any]: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def set_params(self, **params: Any) -> Pipeline: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class ColumnTransformer:
    def __init__(self, transformers: list[tuple[str, Any, list[int]]], remainder: str = "drop") -> None: ...
    def fit(self, x: NDArray[np.float64]) -> ColumnTransformer: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class FeatureUnion:
    def __init__(self, transformer_list: list[tuple[str, Any]]) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> FeatureUnion: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class TextPipeline:
    def __init__(self, steps: list[tuple[str, Any]]) -> None: ...
    def fit(self, documents: list[str], y: NDArray[np.float64]) -> TextPipeline: ...
    def fit_predict(self, documents: list[str], y: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def get_step_names(self) -> list[str]: ...
    def predict(self, documents: list[str]) -> NDArray[np.float64]: ...
    def transform(self, documents: list[str]) -> Any: ...
