from __future__ import annotations

from ferroml import ModelCard

from typing import Any

import numpy as np
from numpy.typing import NDArray

__all__ = [
    "LinearRegression",
    "LogisticRegression",
    "RidgeRegression",
    "LassoRegression",
    "ElasticNet",
    "RobustRegression",
    "QuantileRegression",
    "Perceptron",
    "RidgeCV",
    "LassoCV",
    "ElasticNetCV",
    "RidgeClassifier",
    "IsotonicRegression",
]

class LinearRegression:
    def __init__(
        self,
        fit_intercept: bool = True,
        confidence_level: float = 0.95,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> LinearRegression: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
    def summary(self) -> str: ...
    def r_squared(self) -> float: ...
    def adjusted_r_squared(self) -> float: ...
    def f_statistic(self) -> float: ...
    def residuals(self) -> NDArray[np.float64]: ...
    def fitted_values(self) -> NDArray[np.float64]: ...
    def feature_importance(self) -> NDArray[np.float64]: ...
    def coefficients_with_ci(self, level: float = 0.95) -> list[dict[str, Any]]: ...
    def diagnostics(self) -> str: ...
    def predict_interval(
        self, x: NDArray[np.float64], level: float = 0.95
    ) -> NDArray[np.float64]: ...
    def fit_pandas(
        self, df: Any, target_column: str, feature_columns: list[str] | None = None
    ) -> LinearRegression: ...
    def predict_pandas(
        self, df: Any, feature_columns: list[str] | None = None
    ) -> NDArray[np.float64]: ...
    def fit_sparse(
        self, x: Any, y: NDArray[np.float64]
    ) -> LinearRegression: ...
    def predict_sparse(self, x: Any) -> NDArray[np.float64]: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class LogisticRegression:
    def __init__(
        self,
        fit_intercept: bool = True,
        max_iter: int = 100,
        tol: float = 1e-8,
        l2_penalty: float = 0.0,
        confidence_level: float = 0.95,
        solver: str = "auto",
        compute_diagnostics: bool = True,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> LogisticRegression: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_log_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def decision_function(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
    def summary(self) -> str: ...
    def aic(self) -> float: ...
    def bic(self) -> float: ...
    def log_likelihood(self) -> float: ...
    def pseudo_r_squared(self) -> float: ...
    def odds_ratios(self) -> NDArray[np.float64]: ...
    def odds_ratios_with_ci(self, level: float = 0.95) -> list[dict[str, Any]]: ...
    def likelihood_ratio_test(self) -> float: ...
    def fit_pandas(
        self, df: Any, target_column: str, feature_columns: list[str] | None = None
    ) -> LogisticRegression: ...
    def predict_pandas(
        self, df: Any, feature_columns: list[str] | None = None
    ) -> NDArray[np.float64]: ...
    def predict_proba_pandas(
        self, df: Any, feature_columns: list[str] | None = None
    ) -> NDArray[np.float64]: ...
    def fit_sparse(
        self, x: Any, y: NDArray[np.float64]
    ) -> LogisticRegression: ...
    def predict_sparse(self, x: Any) -> NDArray[np.float64]: ...
    def predict_proba_sparse(self, x: Any) -> NDArray[np.float64]: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class RidgeRegression:
    def __init__(
        self,
        alpha: float = 1.0,
        fit_intercept: bool = True,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> RidgeRegression: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
    def summary(self) -> str: ...
    def r_squared(self) -> float: ...
    def residuals(self) -> NDArray[np.float64]: ...
    def feature_importance(self) -> NDArray[np.float64]: ...
    def fit_pandas(
        self, df: Any, target_column: str, feature_columns: list[str] | None = None
    ) -> RidgeRegression: ...
    def predict_pandas(
        self, df: Any, feature_columns: list[str] | None = None
    ) -> NDArray[np.float64]: ...
    def fit_sparse(
        self, x: Any, y: NDArray[np.float64]
    ) -> RidgeRegression: ...
    def predict_sparse(self, x: Any) -> NDArray[np.float64]: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class LassoRegression:
    def __init__(
        self,
        alpha: float = 1.0,
        fit_intercept: bool = True,
        max_iter: int = 1000,
        tol: float = 1e-4,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> LassoRegression: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
    def summary(self) -> str: ...
    def r_squared(self) -> float: ...
    def n_nonzero(self) -> int: ...
    def feature_importance(self) -> NDArray[np.float64]: ...
    def fit_pandas(
        self, df: Any, target_column: str, feature_columns: list[str] | None = None
    ) -> LassoRegression: ...
    def predict_pandas(
        self, df: Any, feature_columns: list[str] | None = None
    ) -> NDArray[np.float64]: ...
    def fit_sparse(
        self, x: Any, y: NDArray[np.float64]
    ) -> LassoRegression: ...
    def predict_sparse(self, x: Any) -> NDArray[np.float64]: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class ElasticNet:
    def __init__(
        self,
        alpha: float = 1.0,
        l1_ratio: float = 0.5,
        fit_intercept: bool = True,
        max_iter: int = 1000,
        tol: float = 1e-4,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> ElasticNet: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
    def summary(self) -> str: ...
    def r_squared(self) -> float: ...
    def n_nonzero(self) -> int: ...
    def feature_importance(self) -> NDArray[np.float64]: ...
    def fit_pandas(
        self, df: Any, target_column: str, feature_columns: list[str] | None = None
    ) -> ElasticNet: ...
    def predict_pandas(
        self, df: Any, feature_columns: list[str] | None = None
    ) -> NDArray[np.float64]: ...
    def fit_sparse(
        self, x: Any, y: NDArray[np.float64]
    ) -> ElasticNet: ...
    def predict_sparse(self, x: Any) -> NDArray[np.float64]: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class RobustRegression:
    def __init__(
        self,
        estimator: str = "huber",
        max_iter: int = 50,
        tol: float = 1e-6,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> RobustRegression: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class QuantileRegression:
    def __init__(
        self,
        quantile: float = 0.5,
        max_iter: int = 1000,
        tol: float = 1e-6,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> QuantileRegression: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class Perceptron:
    def __init__(
        self,
        max_iter: int = 1000,
        random_state: int | None = None,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> Perceptron: ...
    def partial_fit(
        self,
        x: NDArray[np.float64],
        y: NDArray[np.float64],
        classes: NDArray[np.float64] | None = None,
    ) -> Perceptron: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def decision_function(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...

class RidgeCV:
    def __init__(
        self,
        alphas: list[float] | None = None,
        cv: int = 5,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> RidgeCV: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...

class LassoCV:
    def __init__(
        self,
        n_alphas: int = 100,
        cv: int = 5,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> LassoCV: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...

class ElasticNetCV:
    def __init__(
        self,
        n_alphas: int = 100,
        l1_ratios: list[float] | None = None,
        cv: int = 5,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> ElasticNetCV: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...

class RidgeClassifier:
    def __init__(
        self,
        alpha: float = 1.0,
        fit_intercept: bool = True,
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> RidgeClassifier: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def decision_function(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class IsotonicRegression:
    def __init__(
        self,
        increasing: str = "true",
        y_min: float | None = None,
        y_max: float | None = None,
        out_of_bounds: str = "nan",
    ) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> IsotonicRegression: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
