from __future__ import annotations

import numpy as np
from numpy.typing import NDArray
from typing import Any

class TreeExplainer:
    @staticmethod
    def from_decision_tree_regressor(model: Any) -> TreeExplainer: ...
    @staticmethod
    def from_decision_tree_classifier(model: Any) -> TreeExplainer: ...
    @staticmethod
    def from_random_forest_regressor(model: Any) -> TreeExplainer: ...
    @staticmethod
    def from_random_forest_classifier(model: Any) -> TreeExplainer: ...
    @staticmethod
    def from_gradient_boosting_regressor(model: Any) -> TreeExplainer: ...
    def explain(self, x: NDArray[np.float64]) -> dict[str, Any]: ...
    def explain_batch(self, x: NDArray[np.float64]) -> dict[str, Any]: ...

# Permutation importance
def permutation_importance_rf_reg(model: Any, x: NDArray[np.float64], y: NDArray[np.float64], metric: str = "r2", n_repeats: int = 10, random_state: int | None = None) -> dict[str, Any]: ...
def permutation_importance_rf_clf(model: Any, x: NDArray[np.float64], y: NDArray[np.float64], metric: str = "accuracy", n_repeats: int = 10, random_state: int | None = None) -> dict[str, Any]: ...
def permutation_importance_dt_reg(model: Any, x: NDArray[np.float64], y: NDArray[np.float64], metric: str = "r2", n_repeats: int = 10, random_state: int | None = None) -> dict[str, Any]: ...
def permutation_importance_dt_clf(model: Any, x: NDArray[np.float64], y: NDArray[np.float64], metric: str = "accuracy", n_repeats: int = 10, random_state: int | None = None) -> dict[str, Any]: ...
def permutation_importance_gb_reg(model: Any, x: NDArray[np.float64], y: NDArray[np.float64], metric: str = "r2", n_repeats: int = 10, random_state: int | None = None) -> dict[str, Any]: ...
def permutation_importance_gb_clf(model: Any, x: NDArray[np.float64], y: NDArray[np.float64], metric: str = "accuracy", n_repeats: int = 10, random_state: int | None = None) -> dict[str, Any]: ...
def permutation_importance_linear(model: Any, x: NDArray[np.float64], y: NDArray[np.float64], metric: str = "r2", n_repeats: int = 10, random_state: int | None = None) -> dict[str, Any]: ...
def permutation_importance_logistic(model: Any, x: NDArray[np.float64], y: NDArray[np.float64], metric: str = "accuracy", n_repeats: int = 10, random_state: int | None = None) -> dict[str, Any]: ...
def permutation_importance_et_clf(model: Any, x: NDArray[np.float64], y: NDArray[np.float64], metric: str = "accuracy", n_repeats: int = 10, random_state: int | None = None) -> dict[str, Any]: ...
def permutation_importance_et_reg(model: Any, x: NDArray[np.float64], y: NDArray[np.float64], metric: str = "r2", n_repeats: int = 10, random_state: int | None = None) -> dict[str, Any]: ...

# Partial dependence (1-D)
def partial_dependence_rf_reg(model: Any, x: NDArray[np.float64], feature_idx: int, grid_resolution: int = 50) -> dict[str, Any]: ...
def partial_dependence_rf_clf(model: Any, x: NDArray[np.float64], feature_idx: int, grid_resolution: int = 50) -> dict[str, Any]: ...
def partial_dependence_gb_reg(model: Any, x: NDArray[np.float64], feature_idx: int, grid_resolution: int = 50) -> dict[str, Any]: ...
def partial_dependence_gb_clf(model: Any, x: NDArray[np.float64], feature_idx: int, grid_resolution: int = 50) -> dict[str, Any]: ...
def partial_dependence_dt_reg(model: Any, x: NDArray[np.float64], feature_idx: int, grid_resolution: int = 50) -> dict[str, Any]: ...
def partial_dependence_dt_clf(model: Any, x: NDArray[np.float64], feature_idx: int, grid_resolution: int = 50) -> dict[str, Any]: ...
def partial_dependence_linear(model: Any, x: NDArray[np.float64], feature_idx: int, grid_resolution: int = 50) -> dict[str, Any]: ...

# Partial dependence (2-D)
def partial_dependence_2d_rf_reg(model: Any, x: NDArray[np.float64], feature_idx_1: int, feature_idx_2: int, grid_resolution: int = 20) -> dict[str, Any]: ...
def partial_dependence_2d_gb_reg(model: Any, x: NDArray[np.float64], feature_idx_1: int, feature_idx_2: int, grid_resolution: int = 20) -> dict[str, Any]: ...

# Individual conditional expectation (ICE)
def ice_rf_reg(model: Any, x: NDArray[np.float64], feature_idx: int, n_grid_points: int = 50, center: bool = False, compute_derivative: bool = False) -> dict[str, Any]: ...
def ice_gb_reg(model: Any, x: NDArray[np.float64], feature_idx: int, n_grid_points: int = 50, center: bool = False, compute_derivative: bool = False) -> dict[str, Any]: ...
def ice_dt_reg(model: Any, x: NDArray[np.float64], feature_idx: int, n_grid_points: int = 50, center: bool = False, compute_derivative: bool = False) -> dict[str, Any]: ...
def ice_linear(model: Any, x: NDArray[np.float64], feature_idx: int, n_grid_points: int = 50, center: bool = False, compute_derivative: bool = False) -> dict[str, Any]: ...

# H-statistic (interaction strength)
def h_statistic_rf_reg(model: Any, x: NDArray[np.float64], feature_idx_1: int, feature_idx_2: int, n_grid_points: int = 20) -> dict[str, Any]: ...
def h_statistic_gb_reg(model: Any, x: NDArray[np.float64], feature_idx_1: int, feature_idx_2: int, n_grid_points: int = 20) -> dict[str, Any]: ...
def h_statistic_matrix_rf_reg(model: Any, x: NDArray[np.float64], feature_indices: list[int] | None = None, n_grid_points: int = 20) -> dict[str, Any]: ...

# KernelSHAP (model-agnostic SHAP)
def kernel_shap_rf_reg(model: Any, background: NDArray[np.float64], x: NDArray[np.float64], n_samples: int | None = None, random_state: int | None = None) -> dict[str, Any]: ...
def kernel_shap_rf_clf(model: Any, background: NDArray[np.float64], x: NDArray[np.float64], n_samples: int | None = None, random_state: int | None = None) -> dict[str, Any]: ...
def kernel_shap_dt_reg(model: Any, background: NDArray[np.float64], x: NDArray[np.float64], n_samples: int | None = None, random_state: int | None = None) -> dict[str, Any]: ...
def kernel_shap_dt_clf(model: Any, background: NDArray[np.float64], x: NDArray[np.float64], n_samples: int | None = None, random_state: int | None = None) -> dict[str, Any]: ...
def kernel_shap_gb_reg(model: Any, background: NDArray[np.float64], x: NDArray[np.float64], n_samples: int | None = None, random_state: int | None = None) -> dict[str, Any]: ...
def kernel_shap_gb_clf(model: Any, background: NDArray[np.float64], x: NDArray[np.float64], n_samples: int | None = None, random_state: int | None = None) -> dict[str, Any]: ...
def kernel_shap_linear(model: Any, background: NDArray[np.float64], x: NDArray[np.float64], n_samples: int | None = None, random_state: int | None = None) -> dict[str, Any]: ...
def kernel_shap_logistic(model: Any, background: NDArray[np.float64], x: NDArray[np.float64], n_samples: int | None = None, random_state: int | None = None) -> dict[str, Any]: ...
def kernel_shap_et_clf(model: Any, background: NDArray[np.float64], x: NDArray[np.float64], n_samples: int | None = None, random_state: int | None = None) -> dict[str, Any]: ...
def kernel_shap_et_reg(model: Any, background: NDArray[np.float64], x: NDArray[np.float64], n_samples: int | None = None, random_state: int | None = None) -> dict[str, Any]: ...

__all__ = [
    "TreeExplainer",
    "permutation_importance_rf_reg",
    "permutation_importance_rf_clf",
    "permutation_importance_dt_reg",
    "permutation_importance_dt_clf",
    "permutation_importance_gb_reg",
    "permutation_importance_gb_clf",
    "permutation_importance_linear",
    "permutation_importance_logistic",
    "permutation_importance_et_clf",
    "permutation_importance_et_reg",
    "partial_dependence_rf_reg",
    "partial_dependence_rf_clf",
    "partial_dependence_gb_reg",
    "partial_dependence_gb_clf",
    "partial_dependence_dt_reg",
    "partial_dependence_dt_clf",
    "partial_dependence_linear",
    "partial_dependence_2d_rf_reg",
    "partial_dependence_2d_gb_reg",
    "ice_rf_reg",
    "ice_gb_reg",
    "ice_dt_reg",
    "ice_linear",
    "h_statistic_rf_reg",
    "h_statistic_gb_reg",
    "h_statistic_matrix_rf_reg",
    "kernel_shap_rf_reg",
    "kernel_shap_rf_clf",
    "kernel_shap_dt_reg",
    "kernel_shap_dt_clf",
    "kernel_shap_gb_reg",
    "kernel_shap_gb_clf",
    "kernel_shap_linear",
    "kernel_shap_logistic",
    "kernel_shap_et_clf",
    "kernel_shap_et_reg",
]
