from __future__ import annotations

from ferroml import ModelCard

import numpy as np
from numpy.typing import NDArray

__all__ = ["MultiOutputRegressor", "MultiOutputClassifier"]

class MultiOutputRegressor:
    def __init__(self, estimator: str = "linear_regression") -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> MultiOutputRegressor: ...
    def is_fitted(self) -> bool: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class MultiOutputClassifier:
    def __init__(self, estimator: str = "logistic_regression") -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> MultiOutputClassifier: ...
    def is_fitted(self) -> bool: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_proba(self, x: NDArray[np.float64]) -> list[NDArray[np.float64]]: ...
