from __future__ import annotations

from ferroml import ModelCard
import numpy as np
from numpy.typing import NDArray

__all__ = [
    "GaussianNB",
    "MultinomialNB",
    "BernoulliNB",
    "CategoricalNB",
]

class GaussianNB:
    def __init__(self, var_smoothing: float = 1e-9) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> GaussianNB: ...
    def partial_fit(
        self, x: NDArray[np.float64], y: NDArray[np.float64], classes: NDArray[np.float64] | None = None
    ) -> GaussianNB: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_log_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class MultinomialNB:
    def __init__(self, alpha: float = 1.0, fit_prior: bool = True) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> MultinomialNB: ...
    def fit_sparse(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> MultinomialNB: ...
    def partial_fit(
        self, x: NDArray[np.float64], y: NDArray[np.float64], classes: NDArray[np.float64] | None = None
    ) -> MultinomialNB: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_sparse(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_log_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class BernoulliNB:
    def __init__(self, alpha: float = 1.0, binarize: float = 0.0, fit_prior: bool = True) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> BernoulliNB: ...
    def fit_sparse(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> BernoulliNB: ...
    def partial_fit(
        self, x: NDArray[np.float64], y: NDArray[np.float64], classes: NDArray[np.float64] | None = None
    ) -> BernoulliNB: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_sparse(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_log_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class CategoricalNB:
    def __init__(self, alpha: float = 1.0, fit_prior: bool = True) -> None: ...
    @staticmethod
    def model_card() -> ModelCard: ...

    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> CategoricalNB: ...
    def partial_fit(
        self, x: NDArray[np.float64], y: NDArray[np.float64], classes: NDArray[np.float64] | None = None
    ) -> CategoricalNB: ...
    def predict(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def predict_log_proba(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def score(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> float: ...
