from __future__ import annotations

import numpy as np
from numpy.typing import NDArray
from typing import Any

# Classification metrics
def accuracy_score(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...
def precision_score(y_true: NDArray[np.float64], y_pred: NDArray[np.float64], average: str = "binary") -> float: ...
def recall_score(y_true: NDArray[np.float64], y_pred: NDArray[np.float64], average: str = "binary") -> float: ...
def f1_score(y_true: NDArray[np.float64], y_pred: NDArray[np.float64], average: str = "binary") -> float: ...
def matthews_corrcoef(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...
def cohen_kappa_score(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...
def balanced_accuracy_score(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...
def confusion_matrix(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> NDArray[np.float64]: ...
def classification_report(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> dict[str, Any]: ...

# Regression metrics
def mse(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...
def rmse(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...
def mae(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...
def r2_score(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...
def explained_variance(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...
def max_error(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...
def mape(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...
def median_absolute_error(y_true: NDArray[np.float64], y_pred: NDArray[np.float64]) -> float: ...

# Probabilistic metrics
def roc_auc_score(y_true: NDArray[np.float64], y_score: NDArray[np.float64]) -> float: ...
def pr_auc_score(y_true: NDArray[np.float64], y_score: NDArray[np.float64]) -> float: ...
def average_precision_score(y_true: NDArray[np.float64], y_score: NDArray[np.float64]) -> float: ...
def log_loss(y_true: NDArray[np.float64], y_prob: NDArray[np.float64], eps: float | None = None) -> float: ...
def brier_score(y_true: NDArray[np.float64], y_prob: NDArray[np.float64]) -> float: ...
def brier_skill_score(y_true: NDArray[np.float64], y_prob: NDArray[np.float64]) -> float: ...

# Curve functions
def roc_curve(y_true: NDArray[np.float64], y_score: NDArray[np.float64]) -> tuple[NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]: ...
def precision_recall_curve(y_true: NDArray[np.float64], y_score: NDArray[np.float64]) -> tuple[NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]: ...

# Model comparison
def paired_ttest(scores1: NDArray[np.float64], scores2: NDArray[np.float64]) -> dict[str, Any]: ...
def corrected_resampled_ttest(scores1: NDArray[np.float64], scores2: NDArray[np.float64], n_train: int, n_test: int) -> dict[str, Any]: ...
def mcnemar_test(y_true: NDArray[np.float64], pred1: NDArray[np.float64], pred2: NDArray[np.float64]) -> dict[str, Any]: ...
def wilcoxon_test(scores1: NDArray[np.float64], scores2: NDArray[np.float64]) -> dict[str, Any]: ...

__all__ = [
    "accuracy_score",
    "precision_score",
    "recall_score",
    "f1_score",
    "matthews_corrcoef",
    "cohen_kappa_score",
    "balanced_accuracy_score",
    "confusion_matrix",
    "classification_report",
    "mse",
    "rmse",
    "mae",
    "r2_score",
    "explained_variance",
    "max_error",
    "mape",
    "median_absolute_error",
    "roc_auc_score",
    "pr_auc_score",
    "average_precision_score",
    "log_loss",
    "brier_score",
    "brier_skill_score",
    "roc_curve",
    "precision_recall_curve",
    "paired_ttest",
    "corrected_resampled_ttest",
    "mcnemar_test",
    "wilcoxon_test",
]
