from __future__ import annotations

import numpy as np
from numpy.typing import NDArray
from typing import Any

__all__ = [
    "AutoMLConfig",
    "AutoML",
    "AutoMLResult",
    "LeaderboardEntry",
    "EnsembleResult",
    "EnsembleMember",
]

class AutoMLConfig:
    def __init__(
        self,
        task: str = "classification",
        metric: str = "roc_auc",
        time_budget_seconds: int = 3600,
        cv_folds: int = 5,
        statistical_tests: bool = True,
        confidence_level: float = 0.95,
        multiple_testing: str = "bh",
        seed: int | None = None,
        n_jobs: int | None = None,
    ) -> None: ...
    @property
    def task(self) -> str: ...
    @property
    def metric(self) -> str: ...
    @property
    def time_budget_seconds(self) -> int: ...
    @property
    def cv_folds(self) -> int: ...
    @property
    def statistical_tests(self) -> bool: ...
    @property
    def confidence_level(self) -> float: ...
    @property
    def seed(self) -> int | None: ...

class AutoML:
    def __init__(self, config: AutoMLConfig | None = None) -> None: ...
    @property
    def config(self) -> AutoMLConfig: ...
    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> AutoMLResult: ...

class AutoMLResult:
    @property
    def leaderboard(self) -> list[LeaderboardEntry]: ...
    @property
    def ensemble(self) -> EnsembleResult | None: ...
    @property
    def total_time_seconds(self) -> float: ...
    @property
    def n_successful_trials(self) -> int: ...
    @property
    def n_failed_trials(self) -> int: ...
    @property
    def task(self) -> str: ...
    @property
    def metric_name(self) -> str: ...
    @property
    def maximize(self) -> bool: ...
    @property
    def cv_folds(self) -> int: ...
    def aggregated_importance(self) -> dict[str, Any] | None: ...
    def best_model(self) -> LeaderboardEntry | None: ...
    def best_model_stats(self) -> dict[str, Any] | None: ...
    def competitive_models(self) -> list[LeaderboardEntry]: ...
    def ensemble_improvement(self) -> float | None: ...
    def ensemble_score(self) -> float | None: ...
    def is_successful(self) -> bool: ...
    def model_comparisons(self) -> dict[str, Any] | None: ...
    def models_significantly_different(self, trial_id_1: int, trial_id_2: int) -> bool: ...
    def n_successful_algorithms(self) -> int: ...
    def predict(self, x_train: NDArray[np.float64], y_train: NDArray[np.float64], x_test: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def summary(self) -> str: ...
    def top_features(self, k: int = 5) -> list[tuple[str, float]] | None: ...

class LeaderboardEntry:
    @property
    def rank(self) -> int: ...
    @property
    def trial_id(self) -> int: ...
    @property
    def algorithm(self) -> str: ...
    @property
    def cv_score(self) -> float: ...
    @property
    def cv_std(self) -> float: ...
    @property
    def ci_lower(self) -> float: ...
    @property
    def ci_upper(self) -> float: ...
    @property
    def training_time_seconds(self) -> float: ...
    @property
    def params(self) -> dict[str, Any]: ...

class EnsembleResult:
    @property
    def ensemble_score(self) -> float: ...
    @property
    def improvement(self) -> float: ...
    @property
    def n_models(self) -> int: ...
    @property
    def members(self) -> list[EnsembleMember]: ...

class EnsembleMember:
    @property
    def trial_id(self) -> int: ...
    @property
    def algorithm(self) -> str: ...
    @property
    def weight(self) -> float: ...
    @property
    def selection_count(self) -> int: ...
