"""Export a trained FerroML model for production deployment.

Usage: Claude runs this after training to generate deployment artifacts.
Output: Model files, inference script, FastAPI endpoint, Dockerfile.
"""
from __future__ import annotations

import json
import os
from pathlib import Path


def prepare_deployment(
    model: object,
    model_name: str,
    feature_names: list[str],
    scaler: object | None = None,
    output_dir: str = "./deploy",
) -> dict:
    """Export model and generate deployment templates.

    Parameters
    ----------
    model : object
        Fitted FerroML model.
    model_name : str
        Human-readable name (e.g. "gradient_boosting_v2").
    feature_names : list[str]
        Input feature names in order.
    scaler : object or None
        Optional fitted FerroML scaler to include.
    output_dir : str
        Directory for deployment artifacts.

    Returns
    -------
    dict with files_created, model_size_bytes, inference_template, api_template
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    files_created: list[str] = []
    model_sizes: dict[str, int] = {}

    # --- Save model in multiple formats ---
    for fmt, ext, save_fn in [
        ("json", ".json", "save_json"),
        ("msgpack", ".msgpack", "save_msgpack"),
        ("bincode", ".bin", "save_bincode"),
    ]:
        path = str(out / f"model{ext}")
        try:
            getattr(model, save_fn)(path)
            size = os.path.getsize(path)
            model_sizes[fmt] = size
            files_created.append(path)
        except Exception:
            model_sizes[fmt] = -1  # format not supported

    # Save scaler if provided
    if scaler is not None:
        scaler_path = str(out / "scaler.json")
        try:
            scaler.save_json(scaler_path)
            files_created.append(scaler_path)
        except Exception:
            pass

    # Save feature names
    meta_path = str(out / "metadata.json")
    metadata = {
        "model_name": model_name,
        "feature_names": feature_names,
        "n_features": len(feature_names),
        "has_scaler": scaler is not None,
        "formats": {k: v for k, v in model_sizes.items() if v > 0},
    }
    with open(meta_path, "w") as f:
        json.dump(metadata, f, indent=2)
    files_created.append(meta_path)

    # --- Generate inference.py ---
    model_class = type(model).__name__
    scaler_class = type(scaler).__name__ if scaler else None

    inference_template = _generate_inference(model_class, scaler_class, feature_names)
    inference_path = str(out / "inference.py")
    with open(inference_path, "w") as f:
        f.write(inference_template)
    files_created.append(inference_path)

    # --- Generate FastAPI app ---
    api_template = _generate_api(model_class, scaler_class, feature_names, model_name)
    api_path = str(out / "app.py")
    with open(api_path, "w") as f:
        f.write(api_template)
    files_created.append(api_path)

    # --- Generate requirements.txt ---
    req_template = "ferroml>=1.0.0\nnumpy>=1.24.0\nfastapi>=0.100.0\nuvicorn>=0.23.0\n"
    req_path = str(out / "requirements.txt")
    with open(req_path, "w") as f:
        f.write(req_template)
    files_created.append(req_path)

    # --- Generate Dockerfile ---
    dockerfile_template = _generate_dockerfile(model_name)
    docker_path = str(out / "Dockerfile")
    with open(docker_path, "w") as f:
        f.write(dockerfile_template)
    files_created.append(docker_path)

    return {
        "files_created": files_created,
        "model_size_bytes": model_sizes,
        "inference_template": inference_path,
        "api_template": api_path,
        "model_name": model_name,
        "n_features": len(feature_names),
    }


def _generate_inference(
    model_class: str,
    scaler_class: str | None,
    feature_names: list[str],
) -> str:
    """Generate standalone inference script."""
    scaler_block = ""
    if scaler_class:
        scaler_block = f"""
    # Load scaler
    from ferroml.preprocessing import {scaler_class}
    scaler = {scaler_class}.load_json("scaler.json")
    X = scaler.transform(X)
"""

    return f'''"""FerroML inference script — auto-generated by deploy_model.py."""
from __future__ import annotations

import json

import numpy as np


FEATURE_NAMES = {feature_names!r}


def load_model(path: str = "model.json"):
    """Load the trained model from disk."""
    from ferroml import recommend  # noqa: F401 — ensures ferroml is importable
    # Import the specific model class
    # Adjust the import below if your model lives in a different submodule
    model = None
    for loader_fmt, loader_path in [("json", "model.json"), ("msgpack", "model.msgpack"), ("bincode", "model.bin")]:
        try:
            # FerroML models use ClassName.load_fmt(path)
            import ferroml
            # Generic load attempt — adjust to your model class
            from importlib import import_module
            for submod in ["linear", "trees", "neighbors", "naive_bayes", "svm", "cluster", "neural", "decomposition"]:
                try:
                    mod = import_module(f"ferroml.{{submod}}")
                    cls = getattr(mod, "{model_class}", None)
                    if cls is not None:
                        model = getattr(cls, f"load_{{loader_fmt}}")(loader_path)
                        break
                except (ImportError, AttributeError, Exception):
                    continue
            if model is not None:
                break
        except Exception:
            continue

    if model is None:
        raise RuntimeError("Could not load model from any format")
    return model


def predict(X: np.ndarray, model=None) -> np.ndarray:
    """Run inference on input array.

    Parameters
    ----------
    X : np.ndarray of shape (n_samples, {len(feature_names)})
        Input features in order: {{FEATURE_NAMES}}

    Returns
    -------
    np.ndarray of predictions
    """
    if model is None:
        model = load_model()
{scaler_block}
    return model.predict(X)


if __name__ == "__main__":
    model = load_model()
    # Example: predict on random input
    X_example = np.random.randn(1, {len(feature_names)})
    print("Prediction:", predict(X_example, model))
'''


def _generate_api(
    _model_class: str,
    scaler_class: str | None,
    feature_names: list[str],
    model_name: str,
) -> str:
    """Generate FastAPI endpoint template."""
    return f'''"""FerroML prediction API — auto-generated by deploy_model.py."""
from __future__ import annotations

import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="{model_name} API", version="1.0.0")

FEATURE_NAMES = {feature_names!r}

# Load model at startup
_model = None
_scaler = None


@app.on_event("startup")
def startup():
    global _model, _scaler
    from inference import load_model
    _model = load_model()
{f"""
    from ferroml.preprocessing import {scaler_class}
    _scaler = {scaler_class}.load_json("scaler.json")
""" if scaler_class else ""}


class PredictRequest(BaseModel):
    features: list[list[float]]


class PredictResponse(BaseModel):
    predictions: list[float]
    model_name: str = "{model_name}"
    n_samples: int


@app.post("/predict", response_model=PredictResponse)
def predict(request: PredictRequest):
    """Run model prediction on input features."""
    try:
        X = np.array(request.features, dtype=np.float64)
        if X.shape[1] != {len(feature_names)}:
            raise HTTPException(
                status_code=400,
                detail=f"Expected {{len(FEATURE_NAMES)}} features, got {{X.shape[1]}}",
            )
{"""        if _scaler is not None:
            X = _scaler.transform(X)
""" if scaler_class else ""}
        preds = _model.predict(X)
        return PredictResponse(
            predictions=preds.tolist(),
            n_samples=len(preds),
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/health")
def health():
    return {{"status": "ok", "model_loaded": _model is not None}}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''


def _generate_dockerfile(_model_name: str) -> str:
    """Generate Dockerfile template."""
    return """FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model.json model.msgpack model.bin metadata.json ./
COPY inference.py app.py ./

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
"""


def print_deployment(result: dict) -> None:
    """Print human-readable deployment summary."""
    print(f"\n{'='*60}")
    print(f"DEPLOYMENT PREPARED  |  {result['model_name']}")
    print(f"{'='*60}")
    print(f"\nFeatures: {result['n_features']}")
    print(f"Files created: {len(result['files_created'])}")
    for f in result["files_created"]:
        print(f"  - {f}")
    print(f"\nModel sizes:")
    for fmt, size in result["model_size_bytes"].items():
        if size > 0:
            print(f"  {fmt}: {size:,} bytes")
    print(f"\nTo start the API:")
    print(f"  cd {os.path.dirname(result['api_template'])}")
    print(f"  uvicorn app:app --host 0.0.0.0 --port 8000")
    print()
