from __future__ import annotations
import numpy as np
from numpy.typing import NDArray
from typing import Any

__all__ = [
    "StandardScaler",
    "MinMaxScaler",
    "RobustScaler",
    "MaxAbsScaler",
    "OneHotEncoder",
    "OrdinalEncoder",
    "LabelEncoder",
    "TargetEncoder",
    "SimpleImputer",
    "KNNImputer",
    "PowerTransformer",
    "QuantileTransformer",
    "PolynomialFeatures",
    "KBinsDiscretizer",
    "VarianceThreshold",
    "SelectKBest",
    "SelectFromModel",
    "SMOTE",
    "ADASYN",
    "RandomUnderSampler",
    "RandomOverSampler",
    "RecursiveFeatureElimination",
    "TfidfTransformer",
    "CountVectorizer",
    "TfidfVectorizer",
    "Normalizer",
]

class StandardScaler:
    def __init__(self, with_mean: bool = True, with_std: bool = True) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> StandardScaler: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def inverse_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class MinMaxScaler:
    def __init__(self, feature_range: tuple[float, float] = (0.0, 1.0)) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> MinMaxScaler: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def inverse_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class RobustScaler:
    def __init__(
        self,
        with_centering: bool = True,
        with_scaling: bool = True,
        quantile_range: tuple[float, float] = (25.0, 75.0),
    ) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> RobustScaler: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def inverse_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class MaxAbsScaler:
    def __init__(self) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> MaxAbsScaler: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def inverse_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def export_onnx(
        self,
        path: str,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> None: ...
    def to_onnx_bytes(
        self,
        model_name: str | None = None,
        input_name: str | None = None,
        output_name: str | None = None,
    ) -> bytes: ...

class OneHotEncoder:
    def __init__(self, handle_unknown: str = "error", drop: str | None = None) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> OneHotEncoder: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def inverse_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class OrdinalEncoder:
    def __init__(self, handle_unknown: str = "error") -> None: ...
    def fit(self, x: NDArray[np.float64]) -> OrdinalEncoder: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def inverse_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class LabelEncoder:
    def __init__(self) -> None: ...
    def fit(self, y: NDArray[np.float64]) -> LabelEncoder: ...
    def transform(self, y: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, y: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def inverse_transform(self, y: NDArray[np.float64]) -> NDArray[np.float64]: ...

class TargetEncoder:
    def __init__(self, smooth: float = 1.0, cv: int = 5) -> None: ...
    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> TargetEncoder: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class SimpleImputer:
    def __init__(
        self,
        strategy: str = "mean",
        fill_value: float = 0.0,
        missing_values: float | None = None,
        add_indicator: bool = False,
    ) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> SimpleImputer: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def get_missing_counts(self) -> NDArray[np.float64]: ...

class KNNImputer:
    def __init__(self, n_neighbors: int = 5, weights: str = "uniform") -> None: ...
    def fit(self, x: NDArray[np.float64]) -> KNNImputer: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class PowerTransformer:
    def __init__(self, method: str = "yeo-johnson") -> None: ...
    def fit(self, x: NDArray[np.float64]) -> PowerTransformer: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def inverse_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class QuantileTransformer:
    def __init__(self, output_distribution: str = "uniform", n_quantiles: int = 1000) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> QuantileTransformer: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def inverse_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class PolynomialFeatures:
    def __init__(self, degree: int = 2) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> PolynomialFeatures: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class KBinsDiscretizer:
    def __init__(self, n_bins: int = 5, strategy: str = "quantile", encode: str = "ordinal") -> None: ...
    def fit(self, x: NDArray[np.float64]) -> KBinsDiscretizer: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class VarianceThreshold:
    def __init__(self, threshold: float = 0.0) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> VarianceThreshold: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class SelectKBest:
    def __init__(self, score_func: str = "f_classif", k: int = 10) -> None: ...
    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> SelectKBest: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class SelectFromModel:
    def __init__(
        self,
        importances: NDArray[np.float64],
        threshold: str = "mean",
        max_features: int | None = None,
    ) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> SelectFromModel: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def get_support(self) -> NDArray[np.float64]: ...

class SMOTE:
    def __init__(
        self,
        k_neighbors: int = 5,
        sampling_strategy: str = "auto",
        random_state: int | None = None,
    ) -> None: ...
    def fit_resample(
        self, x: NDArray[np.float64], y: NDArray[np.float64]
    ) -> tuple[NDArray[np.float64], NDArray[np.float64]]: ...

class ADASYN:
    def __init__(
        self,
        k_neighbors: int = 5,
        n_neighbors: int = 5,
        sampling_strategy: str = "auto",
        random_state: int | None = None,
    ) -> None: ...
    def fit_resample(
        self, x: NDArray[np.float64], y: NDArray[np.float64]
    ) -> tuple[NDArray[np.float64], NDArray[np.float64]]: ...

class RandomUnderSampler:
    def __init__(
        self,
        sampling_strategy: str = "auto",
        replacement: bool = False,
        random_state: int | None = None,
    ) -> None: ...
    def fit_resample(
        self, x: NDArray[np.float64], y: NDArray[np.float64]
    ) -> tuple[NDArray[np.float64], NDArray[np.float64]]: ...

class RandomOverSampler:
    def __init__(
        self,
        sampling_strategy: str = "auto",
        shrinkage: float | None = None,
        random_state: int | None = None,
    ) -> None: ...
    def fit_resample(
        self, x: NDArray[np.float64], y: NDArray[np.float64]
    ) -> tuple[NDArray[np.float64], NDArray[np.float64]]: ...

class RecursiveFeatureElimination:
    def __init__(self) -> None: ...
    def fit(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> RecursiveFeatureElimination: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64], y: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @staticmethod
    def with_linear_regression(
        n_features_to_select: int | None = None, step: int = 1, fit_intercept: bool = True
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_ridge(
        n_features_to_select: int | None = None, step: int = 1, alpha: float = 1.0
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_lasso(
        n_features_to_select: int | None = None, step: int = 1, alpha: float = 1.0
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_logistic_regression(
        n_features_to_select: int | None = None, step: int = 1, max_iter: int = 100
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_decision_tree_classifier(
        n_features_to_select: int | None = None,
        step: int = 1,
        max_depth: int | None = None,
        min_samples_split: int = 2,
        min_samples_leaf: int = 1,
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_decision_tree_regressor(
        n_features_to_select: int | None = None,
        step: int = 1,
        max_depth: int | None = None,
        min_samples_split: int = 2,
        min_samples_leaf: int = 1,
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_random_forest_classifier(
        n_features_to_select: int | None = None,
        step: int = 1,
        n_estimators: int = 100,
        max_depth: int | None = None,
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_random_forest_regressor(
        n_features_to_select: int | None = None,
        step: int = 1,
        n_estimators: int = 100,
        max_depth: int | None = None,
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_extra_trees_classifier(
        n_features_to_select: int | None = None,
        step: int = 1,
        n_estimators: int = 100,
        max_depth: int | None = None,
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_extra_trees_regressor(
        n_features_to_select: int | None = None,
        step: int = 1,
        n_estimators: int = 100,
        max_depth: int | None = None,
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_gradient_boosting_classifier(
        n_features_to_select: int | None = None,
        step: int = 1,
        n_estimators: int = 100,
        max_depth: int = 3,
        learning_rate: float = 0.1,
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_gradient_boosting_regressor(
        n_features_to_select: int | None = None,
        step: int = 1,
        n_estimators: int = 100,
        max_depth: int = 3,
        learning_rate: float = 0.1,
    ) -> RecursiveFeatureElimination: ...
    @staticmethod
    def with_svr(
        n_features_to_select: int | None = None,
        step: int = 1,
        c: float = 1.0,
        epsilon: float = 0.1,
    ) -> RecursiveFeatureElimination: ...

class TfidfTransformer:
    def __init__(
        self,
        norm: str = "l2",
        use_idf: bool = True,
        smooth_idf: bool = True,
        sublinear_tf: bool = False,
    ) -> None: ...
    def fit(self, x: NDArray[np.float64]) -> TfidfTransformer: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_sparse(self, x: NDArray[np.float64]) -> TfidfTransformer: ...
    def transform_sparse(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform_sparse(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...

class CountVectorizer:
    def __init__(
        self,
        max_features: int | None = None,
        min_df: int = 1,
        max_df: float = 1.0,
        ngram_range: tuple[int, int] = (1, 1),
        binary: bool = False,
        lowercase: bool = True,
        stop_words: list[str] | None = None,
    ) -> None: ...
    def fit(self, documents: list[str]) -> CountVectorizer: ...
    def transform(self, documents: list[str]) -> NDArray[np.float64]: ...
    def fit_transform(self, documents: list[str]) -> NDArray[np.float64]: ...
    def get_feature_names_out(self) -> list[str]: ...

class TfidfVectorizer:
    def __init__(
        self,
        max_features: int | None = None,
        min_df: int = 1,
        max_df: float = 1.0,
        ngram_range: tuple[int, int] = (1, 1),
        binary: bool = False,
        lowercase: bool = True,
        stop_words: list[str] | None = None,
        norm: str = "l2",
        use_idf: bool = True,
        smooth_idf: bool = True,
        sublinear_tf: bool = False,
    ) -> None: ...
    def fit(self, documents: list[str]) -> TfidfVectorizer: ...
    def transform(self, documents: list[str]) -> NDArray[np.float64]: ...
    def fit_transform(self, documents: list[str]) -> NDArray[np.float64]: ...
    def transform_dense(self, documents: list[str]) -> NDArray[np.float64]: ...
    def get_feature_names_out(self) -> list[str]: ...

class Normalizer:
    def __init__(self, norm: str = "l2") -> None: ...
    def fit(self, x: NDArray[np.float64]) -> Normalizer: ...
    def transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
